language: node_js

sudo: enabled

matrix:
  include:
    # Test LTS node
    - os: linux
      node_js: lts/*
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    # Test latest node
    - os: linux
      node_js: node
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
- sudo apt-get install xvfb libgirepository1.0-dev gobject-introspection build-essential g++-7
- eval "${MATRIX_EVAL}"

install:
- npm install

script:
- npm run build
