language: node_js
node_js:
- lts/*
- node # latest

os: linux
sudo: false

env:
- CC=gcc-8
- CXX=g++-8

addons:
  apt:
    sources:
      sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - xfvb
    - libgirepository1.0-dev
    - gobject-introspection
    - build-essential
    - g++-8

before_install:
- eval "${MATRIX_EVAL}"

install:
- npm install

script:
- npm run build
