language: node_js

sudo: enabled

matrix:
  include:
    # Test node v8
    - os: linux
      node_js: 8
    # Test node v10
    - os: linux
      node_js: 10

before_install:
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
- sudo apt-get install xvfb libgirepository1.0-dev gobject-introspection build-essential

install:
- npm install

script:
- npm run build
